services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    command: gunicorn --bind :${PORT:-8000} --workers 2 paky.wsgi
    volumes:
      - .:/code
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    depends_on:
      - valkey
  valkey:
    image: valkey/valkey
    ports:
      - "6379:6379"
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    command: celery -A paky worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - valkey