# Generated by Django 5.1.3 on 2024-11-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name_plural': 'Setores'},
        ),
    ]
